language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
install:
  - travis_retry pip install -q $DJANGO
  - python setup.py install
script: python manage.py test rest_framework_filters

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
  fast_finish: true
