language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install detox tox-travis tox-venv coverage
script:
  - detox
after_success:
  - coverage report
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - python: "3.6"
      env: TOXENV="performance"
    - python: "3.6"
      env: TOXENV="warnings"
    - python: "3.6"
      env: TOXENV="isort,lint"

  allow_failures:
    - env: TOXENV="warnings"
  fast_finish: true
