language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
install:
  - travis_retry pip install -q $DJANGO "coverage==3.7.1"
  - pip install .
script:
  - coverage run manage.py test
  - coverage report

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
  fast_finish: true
