language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO="django<1.5" # Django 1.4
  - DJANGO="django<1.6" # Django 1.5
install:
  - pip install -q $DJANGO --use-mirrors
  - python setup.py develop
script: python manage.py test rest_framework_chain

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django<1.5"
    - python: "3.3"
      env: DJANGO="django<1.5"
